version: "3"
services:
  #PHP Service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php:8.0.3-fpm-buster
    container_name: app6
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "6001:6001"

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver6
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8084:80"
      - "445:443"

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db6
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database-local/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "10004:3306"

  #Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - "6084:8080"
